fail_fast: true

repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: poetry run bash scripts/lint.sh
        language: system
        files: ^src/zenml/|^tests/|^examples/
        types: [file, python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run bash scripts/test-coverage-xml.sh
        language: system
        files: ^src/zenml/|^tests/|^examples/
        types: [file, python]
        pass_filenames: false

  -   repo: https://github.com/codespell-project/codespell
      rev: v2.1.0
      hooks:
      -   id: codespell
          name: codespell
          description: Checks for common misspellings in text files.
          entry: codespell -c -I .codespell-ignore-words -f -i 0 --builtin clear,rare,en-GB_to_en-US,names,code CODE-OF-CONDUCT.md CONTRIBUTING.md ROADMAP.md README.md RELEASE_NOTES.md src/ docs/book examples/