- description: Steps using ZenML's `great_expectations` data validator integration.
    These allow you to run data profiling and data quality tests on the data circulated
    through your pipelines.
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/data_validator/greatexpectations.jpeg
  name: great_expectations_steps
  repository_subdirectory: src/great_expectations_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's Slack alerter integration. These steps allow you
    to send messages to Slack when events happen during or after your pipeline runs.
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/alerter/slack.png
  name: slack_steps
  repository_subdirectory: src/slack_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's `bentoml` integration, which allows you to deploy
    models locally, in a cloud environment or onto a Kubernetes cluster.
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/model_deployer/bentoml.png
  name: bentoml_steps
  repository_subdirectory: src/bentoml_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's `kserve` integration, which allows you to deploy
    and manage models on an inference server running on top of a Kubernetes cluster.
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/model_deployer/kserve.png
  name: kserve_steps
  repository_subdirectory: src/kserve_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's `evidently` data validator integration, which allow
    you to perform data quality, data drift, model drift and model performance analyses,
    to generate reports and run checks. The reports and check results can be used
    to implement automated corrective actions in your pipelines or to render interactive
    representations for further visual interpretation, evaluation and documentation.
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/data_validator/evidently.png
  name: evidently_steps
  repository_subdirectory: src/evidently_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's `whylogs` data validator integration, which allow
    you to generate and track data profiles, highly accurate descriptive representations
    of your data. The profiles can be used to implement automated corrective actions
    in your pipelines, or to render interactive representations for further visual
    interpretation, evaluation and documentation.
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/data_validator/whylogs.png
  name: whylogs_steps
  repository_subdirectory: src/whylogs_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's `label_studio` integration, which allows you to
    label data in a web-based UI. It is used to create or edit datasets that you can
    then use as part of training or validation workflows. It supports a broad range
    of annotation types (including custom types).
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/annotator/label_studio.png
  name: label_studio_steps
  repository_subdirectory: src/label_studio_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's `mlflow` experiment tracker integration, which
    allows you to log and visualize information from your pipeline steps (e.g. models,
    parameters, metrics).
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/model_deployer/mlflow.png
  name: mlflow_steps
  repository_subdirectory: src/mlflow_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's Seldon integration, which can be used to deploy
    and manage models on an inference server running on top of a Kubernetes cluster.
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/model_deployer/seldon.png
  name: seldon_steps
  repository_subdirectory: src/seldon_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
- description: Steps using ZenML's Deepchecks data validator integration which allow
    you to run data integrity, data drift, model drift and model performance tests
    on the datasets and models circulated in your ZenML pipelines. The test results
    can be used to implement automated corrective actions in your pipelines or to
    render interactive representations for further visual interpretation, evaluation
    and documentation.
  logo_url: https://public-flavor-logos.s3.eu-central-1.amazonaws.com/data_validator/deepchecks.png
  name: deepchecks_steps
  repository_subdirectory: src/deepchecks_steps
  repository_url: https://github.com/zenml-io/zenml-hub-plugins
  tags: []
