# This is a basic workflow to help you get started with Actions
name: Main

# Controls when the action will run. Triggers the workflow on push of a tag
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry"

      - name: Install Dependencies
        run: python -m poetry install

      - name: Lint
        run: python -m poetry run bash scripts/lint.sh

      - name: Test
        run: python -m poetry run bash scripts/test-coverage-xml.sh

      - name: Upload coverage
        # only do it for python 3.6, we don't need to do it for every version
        if: ${{ matrix.python-version == '3.6' }}
        uses: codecov/codecov-action@v2