# This is a basic workflow to help you get started with Actions
name: Tests on Main

# Controls when the action will run. Triggers the workflow on push of a tag
on:
  push:
    branches:
      - main
      - alexej/ENG-234-zenml-integration-install

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    runs-on: ${{ matrix.os }}
    # Exit if its a commit from Gitbook
    if: ${{ ! startsWith(github.event.head_commit.message, 'GitBook:') }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry"

      - name: Delete error-causing bash
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          rm.exe "C:/WINDOWS/system32/bash.EXE"

      - name: Install Dependencies
        run: |
          python -m poetry install
          python -m poetry run zenml integration install airflow -f
          python -m poetry run zenml integration install pytorch -f
          python -m poetry run zenml integration install gcp -f
          python -m poetry run pip install click~=8.0.3
          

      - name: Opt-out of analytics
        run: |
          python -m poetry run zenml analytics opt-out

      - name: Lint
        run: |
          python -m poetry run bash scripts/lint.sh

      - name: Test
        run: python -m poetry run bash scripts/test-coverage-xml.sh

      - name: Upload coverage
        # only do it for python 3.6, we don't need to do it for every version
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2