# This is a basic workflow that publishes the website
name: Publish

# Controls when the action will run.
on:
  push:
    branches:
      - hamza/deploy-api-reference

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    name: Build and publishes the api docs reference to S3
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zenml-io/zenml-static-hosting-jekyll-aws:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install "poetry"

    - name: Install Dependencies
      run: |
        python -m poetry install
        python -m poetry run pip install apache-airflow~=2.2.0 gcsfs~=2021.9.0 click~=8.0.3 torch~=1.10.0

    - name: Runs docs generation
      run: ./scripts/generate-docs.py

    - name: Runs deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET=testapidocs.zenml.io
        CLOUDFRONT_DISTRIBUTION_ID=E1VI10FL4K97QY
      run: ./scripts/deploy-docs.py