# This is a basic workflow to help you get started with Actions
name: Publish

# Controls when the action will run. Triggers the workflow on push of a tag
on:
  push:
    branches:
      - main
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-20.04
    steps:
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry"

      - name: Install Dependencies
        run: python -m poetry install

      - name: Lint
        run: python -m poetry run bash scripts/lint.sh

      - name: Test
        run: python -m poetry run bash scripts/test-coverage-xml.sh

      # Runs a set of commands using the runners shell
      - name: publish
        env: # Or as an environment variable
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          if [ "$(cat zenml/VERSION)" = "$(echo ${GITHUB_REF} | sed 's|refs/tags/||g')" ]; then ./scripts/publish.sh; else exit 1; fi