name: Testing

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry"

      - name: Install Dependencies
        run: |
          python -m poetry install
          python -m poetry run pip install apache-airflow~=2.2.0 gcsfs~=2021.9.0

      - name: Lint
        run: |
          python -m poetry run bash scripts/lint.sh
          python -m poetry run bash scripts/type_checker.sh --install-types

      - name: Test
        run: python -m poetry run bash scripts/test-coverage-xml.sh

      - name: Upload coverage
        # only do it for python 3.6, we don't need to do it for every version
        if: ${{ matrix.python-version == '3.8' }}
        uses: codecov/codecov-action@v2