name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-root

      - name: Install poetry
        if: steps.cache.outputs.cache-hit != 'true'
        # TODO: remove python -m pip install --force git+https://github.com/python-poetry/poetry-core.git@ad33bc2
        # once there's a release of Poetry 1.2.x including poetry-core > 1.1.0a6
        # Ref: https://github.com/python-poetry/poetry-core/pull/188
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry"

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m poetry install

      - name: Lint
        if: ${{ matrix.python-version != '3.6' }}
        run: python -m poetry run bash scripts/lint.sh

      - name: Test
        run: python -m poetry run bash scripts/test-coverage-xml.sh
        
      - name: Upload coverage
        uses: codecov/codecov-action@v1