# This is a basic workflow to help you get started with Actions
name: Release Package & Docker Image

# Controls when the action will run. Triggers the workflow on push of a tag
on:
  push:
    tags:
      - '*'

jobs:
  publish-python-package:
    uses: ./.github/workflows/publish_to_pypi.yml
    secrets: inherit

  wait-for-package-release:
    runs-on: ubuntu-latest
    needs: publish-python-package
    steps:
      - name: Sleep for 2 minutes
        run: sleep 120
        shell: bash

  publish-docker-image:
    needs: wait-for-package-release
    uses: ./.github/workflows/publish_docker_image.yml
    secrets: inherit
