name: Cloudbuild-Test

on:
  push:
    branches:
      - michael/ENG-198-cloudbuild-fixes

jobs:
  cloudbuild:
    name: Cloudbuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_CLOUDBUILD_EMAIL }}
          service_account_key: ${{ secrets.GCP_CLOUDBUILD_KEY }}
          project_id: ${{ secrets.GCP_CLOUDBUILD_PROJECT }}

      # Cloudbuild
      - name: Build docker images
        run: |-
          gcloud builds submit \
            --quiet \
            --config=cloudbuild.yaml \
            --substitutions=TAG_NAME=0.5.3 .
