apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql
  labels:
    app: cloudsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsql
  template:
    metadata:
      labels:
        app: cloudsql
    spec:
      containers:
      - name: cloudsql
        image: gcr.io/cloudsql-docker/gce-proxy:1.10
        command: ["/cloud_sql_proxy",
                  "-instances=PROJECT:REGION:INSTANCE=tcp:0.0.0.0:3306",
                  "-credential_file=/secrets/cloudsql/key.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: zenml-cloudsql-key
---
kind: Service
apiVersion: v1
metadata:
  name: sql-proxy-service
spec:
  selector:
    app: cloudsql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306